baseURL = "https://tom.britton.dev"
languageCode = "en-us"
title = "Tom Britton Dot Dev"
theme = "simple-hugo-theme"
publishDir = "docs"

[params] 
  custom_css = ["css/tbr.css"]
# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
